// 2-BOSQICH: KENGAYTIRILGAN SAVOLLAR BAZASI
// Format:
// ["Savol", "TO‘G‘RI javob", "Xato 1", "Xato 2", "Xato 3"]

const Q = {

"Umumiy": [
["Quyosh sistemasidagi eng katta sayyora qaysi?","Yupiter","Saturn","Mars","Neptun"],
["Suvning kimyoviy formulasi qanday?","H₂O","CO₂","O₂","NaCl"],
["Kattalar tanasida nechta suyak bor?","206","106","306","150"],
["Quruqlikdagi eng tez hayvon qaysi?","Gepard","Sher","Ot","Yo‘lbars"],
["Kamalakda nechta rang bor?","7","5","6","8"],
["Eng katta okean qaysi?","Tinch okeani","Atlantika","Hind","Shimoliy Muz"],
["Yerning tabiiy yo‘ldoshi nima?","Oy","Quyosh","Mars","Venera"],
["Inson yuragida nechta kamera bor?","4","2","3","5"],
["Bir sutkada necha soat bor?","24","12","36","48"],
["Bir haftada necha kun bor?","7","5","6","8"],
["Dunyodagi eng katta sutemizuvchi hayvon qaysi?","Ko‘k kit","Fil","Jirafa","Akula"],
["Inson nafas olishda qaysi gazdan foydalanadi?","Kislorod","Azot","Karbonat angidrid","Vodorod"],
["Muzning erish harorati necha °C?","0","10","-10","100"],
["Suv dengiz sathida taxminan necha °C da qaynaydi?","100","50","90","120"],
["Quyoshga eng yaqin sayyora qaysi?","Merkuriy","Venera","Mars","Yer"],
["Qaysi hayvon sutemizuvchi hisoblanadi?","Delfin","Akula","Timsoh","Pingvin"],
["Inson tanasidagi eng katta a’zo qaysi?","Teri","Yurak","Jigar","O‘pka"],
["Yer Quyosh atrofini taxminan qancha vaqtda aylanib chiqadi?","365 kun","30 kun","180 kun","700 kun"],
["Asalarilar nima ishlab chiqaradi?","Asal","Sut","Ipak","Mum faqat"],
["Odamning normal tana harorati taxminan qancha?","36–37°C","30°C","40–42°C","25°C"]
],

"Tarix": [
["Amir Temur qaysi yili tug‘ilgan?","1336","1240","1405","1500"],
["Mirzo Ulug‘bek qaysi fan sohasida mashhur?","Astronomiya","Kimyo","Tibbiyot","Dengizchilik"],
["O‘zbekiston mustaqilligi qaysi yili e’lon qilingan?","1991","1990","1992","1989"],
["Birinchi jahon urushi qaysi yili boshlangan?","1914","1918","1939","1905"],
["Alisher Navoiy qaysi asrda yashagan?","XV asr","X asr","XIX asr","XII asr"],
["Kolumb Amerikaga qaysi yili yetib borgan?","1492","1392","1592","1453"],
["Ikkinchi jahon urushi qaysi yili boshlangan?","1939","1914","1941","1945"],
["Amir Temur saltanatining poytaxti qaysi shahar bo‘lgan?","Samarqand","Buxoro","Toshkent","Xiva"],
["Buyuk Ipak yo‘li asosan nimani bog‘lagan?","Sharq va G‘arbni","Shimol va Janubni","Afrika va Amerikani","Faqat Yevropani"],
["Misr piramidalari asosan nima uchun qurilgan?","Maqbaralar sifatida","Saroy sifatida","Bozor sifatida","Qal’a sifatida"],
["Leonardo da Vinchi qaysi mashhur asarni yaratgan?","Mona Liza","Guernica","Qichqiriq","Yulduzli tun"],
["Fransuz inqilobi qaysi yilda boshlangan?","1789","1689","1812","1917"],
["Qadimgi Rimning asosiy tili qaysi bo‘lgan?","Lotin tili","Arab tili","Ingliz tili","Xitoy tili"],
["Chingizxon qaysi imperiyaga asos solgan?","Mo‘g‘ullar imperiyasi","Rim imperiyasi","Usmonlilar imperiyasi","Vizantiya"],
["Berlin devori qaysi yili qulagan?","1989","1979","1991","1961"],
["Sovet Ittifoqi qaysi yili parchalanib ketgan?","1991","1989","1995","2000"],
["Napoleon Bonapart qaysi davlat tarixida mashhur?","Fransiya","Ispaniya","Italiya","Angliya"],
["Buyuk Britaniya qirolichasi Yelizaveta II qaysi yilda taxtga chiqqan?","1952","1945","1960","1970"],
["Qadimgi Olimpiya o‘yinlari qaysi davlatda boshlangan?","Yunoniston","Italiya","Misr","Xitoy"],
["Samarqanddagi Registon majmuasi asosan qaysi davr bilan bog‘liq?","Temuriylar davri","Rim davri","Vikinglar davri","Misr davri"]
],

"Geografiya": [
["Dunyodagi eng baland tog‘ qaysi?","Everest","K2","Elbrus","Monblan"],
["Eng katta qit’a qaysi?","Osiyo","Afrika","Yevropa","Shimoliy Amerika"],
["Yaponiya poytaxti qaysi shahar?","Tokio","Pekin","Seul","Bangkok"],
["Fransiya poytaxti qaysi shahar?","Parij","Rim","Madrid","Berlin"],
["Sahroi Kabir qaysi qit’ada joylashgan?","Afrika","Osiyo","Avstraliya","Janubiy Amerika"],
["Eng kichik qit’a qaysi?","Avstraliya","Yevropa","Antarktida","Janubiy Amerika"],
["Rossiyaning poytaxti qaysi shahar?","Moskva","Sankt-Peterburg","Qozon","Sochi"],
["Italiyaning poytaxti qaysi shahar?","Rim","Milan","Venetsiya","Neapol"],
["Germaniyaning poytaxti qaysi shahar?","Berlin","Myunxen","Gamburg","Frankfurt"],
["Turkiyaning poytaxti qaysi shahar?","Anqara","Istanbul","Izmir","Antaliya"],
["Nil daryosi qaysi qit’ada joylashgan?","Afrika","Osiyo","Yevropa","Janubiy Amerika"],
["Amazonka daryosi asosan qaysi qit’ada?","Janubiy Amerika","Afrika","Osiyo","Yevropa"],
["Dunyodagi eng katta orol qaysi?","Grenlandiya","Madagaskar","Borneo","Yangi Gvineya"],
["Hindiston poytaxti qaysi?","Dehli","Mumbay","Kolkata","Chennay"],
["Xitoy poytaxti qaysi?","Pekin","Shanxay","Guanchjou","Shenchjen"],
["AQSh poytaxti qaysi?","Vashington","Nyu-York","Los-Anjeles","Chikago"],
["Ispaniya poytaxti qaysi?","Madrid","Barselona","Sevilya","Valensiya"],
["Braziliya poytaxti qaysi?","Brasiliya","Rio-de-Janeyro","San-Paulu","Salvador"],
["Misr poytaxti qaysi?","Qohira","Iskandariya","Giza","Luksor"],
["Qaysi davlat ikki qit’ada joylashgan?","Turkiya","Portugaliya","Yaponiya","Avstraliya"]
],

"O‘zbekiston": [
["O‘zbekiston poytaxti qaysi shahar?","Toshkent","Samarqand","Buxoro","Xiva"],
["Registon maydoni qaysi shaharda?","Samarqand","Buxoro","Xiva","Toshkent"],
["Navro‘z bayrami qaysi faslda nishonlanadi?","Bahorda","Yozda","Kuzda","Qishda"],
["O‘zbekistonning pul birligi qaysi?","So‘m","Rubl","Dollar","Tenge"],
["Ichan-Qal’a qaysi shaharda joylashgan?","Xiva","Qo‘qon","Termiz","Nukus"],
["Qoraqalpog‘iston poytaxti qaysi shahar?","Nukus","Urganch","Termiz","Navoiy"],
["O‘zbekiston nechta davlat bilan chegaradosh?","5","3","4","7"],
["O‘zbekistonning eng katta shahri qaysi?","Toshkent","Samarqand","Andijon","Namangan"],
["Amudaryo O‘zbekistonning qaysi hududlari orqali oqadi?","G‘arbiy va janubiy hududlari","Faqat Toshkent","Faqat Farg‘ona","Faqat Andijon"],
["Buxoro qaysi tarixiy obidasi bilan mashhur?","Ark qal’asi","Registon","Ichan-Qal’a","Minorai Kalon emas"],
["Samarqand qaysi tarixiy shaxs davrida yirik markazga aylangan?","Amir Temur","Napoleon","Chingizxon","Kolumb"],
["O‘zbekiston bayrog‘ida nechta yulduz bor?","12","10","11","15"],
["O‘zbekiston gerbining markazida qaysi afsonaviy qush tasvirlangan?","Humo","Burgut","Lochin","Turna"],
["O‘zbekiston Konstitutsiyasi qaysi yili qabul qilingan?","1992","1991","1993","1990"],
["O‘zbekiston madhiyasi musiqasini kim bastalagan?","Mutal Burhonov","Yunus Rajabiy","Komiljon Otaniyozov","Mansur Toshmatov"],
["Xiva qaysi hududning tarixiy markazlaridan biri?","Xorazm","Farg‘ona","Surxondaryo","Toshkent"],
["Qo‘qon shahri qaysi vodiyda joylashgan?","Farg‘ona vodiysi","Zarafshon vodiysi","Qashqadaryo vodiysi","Surxon vodiysi"],
["O‘zbekistonning eng baland nuqtasi qaysi tog‘ tizmasida?","Hisor","Ural","Alp","Kavkaz"],
["Orol dengizi asosan qaysi hududlar oralig‘ida joylashgan?","O‘zbekiston va Qozog‘iston","O‘zbekiston va Tojikiston","Qozog‘iston va Rossiya","Turkmaniston va Eron"],
["Termiz qaysi daryo bo‘yida joylashgan?","Amudaryo","Sirdaryo","Zarafshon","Chirchiq"]
],

"Texnologiya": [
["Telegram qaysi yili ishga tushgan?","2013","2008","2016","2010"],
["Android operatsion tizimi qaysi kompaniyaga tegishli?","Google","Apple","Microsoft","Nokia"],
["1 bayt necha bitdan iborat?","8","4","10","16"],
["Kompyuterning ‘miyasi’ deb qaysi qism aytiladi?","Protsessor","Monitor","Klaviatura","Sichqoncha"],
["GitHub nima uchun ishlatiladi?","Kodni saqlash va ulashish","Video ko‘rish","Pul o‘tkazish","Rasm chizish"],
["Wi-Fi ma’lumotni nima orqali uzatadi?","Radio to‘lqinlari","Faqat optik kabel","Tovush","Quyosh nuri"],
["HTML asosan nima uchun ishlatiladi?","Veb-sahifa tuzilmasi uchun","Rasm tahrirlash uchun","Video montaj uchun","Antivirus sifatida"],
["CSS nima uchun ishlatiladi?","Veb-sahifa ko‘rinishini bezash","Ma’lumotlar bazasini o‘chirish","Video yozish","Fayl siqish"],
["JavaScript asosan nima uchun ishlatiladi?","Veb-sahifaga interaktivlik berish","Kompyuterni zaryadlash","Rasm chop etish","Internet kabeli sifatida"],
["URL nimani anglatadi?","Internetdagi manzil","Kompyuter virusi","Fayl turi","Parol tizimi"],
["QR-kod odatda nima uchun ishlatiladi?","Ma’lumot yoki havolani tez ochish","Telefonni zaryadlash","Ovoz kuchaytirish","Rasmni kattalashtirish"],
["USB nimaga ulanish uchun keng ishlatiladi?","Qurilmalar va ma’lumot almashish","Faqat televizorga","Faqat internetga","Faqat printerga"],
["SSD nimasi bilan HDDdan farq qiladi?","Harakatlanuvchi mexanik qismlari yo‘q","Faqat magnitdan ishlaydi","Faqat internet bilan ishlaydi","Faqat telefonlarda bo‘ladi"],
["Bulutli saqlash nima?","Ma’lumotni internetdagi serverlarda saqlash","Faylni qog‘ozga chiqarish","Kompyuterni o‘chirish","Internetni tezlashtirish"],
["Sun’iy intellekt nimani anglatadi?","Kompyuterlarning murakkab vazifalarni bajarish texnologiyasi","Faqat robot o‘yinchoq","Internet turi","Telefon modeli"],
["Bluetooth asosan nima uchun ishlatiladi?","Qurilmalar orasida simsiz aloqa","Sun’iy yo‘ldosh uchirish","Internet kabeli","Elektr ishlab chiqarish"],
["VPN nima uchun ishlatilishi mumkin?","Internet ulanishini himoyalash va yo‘naltirish","Telefon batareyasini almashtirish","Rasm chizish","Printer tozalash"],
["Google Chrome nima?","Veb-brauzer","Operatsion tizim","Antivirus","Telefon ishlab chiqaruvchisi"],
["Windows qaysi kompaniya mahsuloti?","Microsoft","Google","Apple","Samsung"],
["iPhone qaysi kompaniya tomonidan ishlab chiqariladi?","Apple","Google","Microsoft","Huawei"]
],

"Fan": [
["Suvning kimyoviy formulasi qanday?","H₂O","CO₂","O₂","NaCl"],
["Kislorodning kimyoviy belgisi qaysi?","O","K","C","N"],
["Oltinning kimyoviy belgisi qaysi?","Au","Ag","Fe","Cu"],
["Temirning kimyoviy belgisi qaysi?","Fe","Ir","Ti","Al"],
["Yerning tortishish tezlanishi taxminan qancha?","9,8 m/s²","5 m/s²","15 m/s²","20 m/s²"],
["Elektr toki kuchining o‘lchov birligi nima?","Amper","Volt","Om","Vatt"],
["Kuchlanishning o‘lchov birligi nima?","Volt","Amper","Om","Joul"],
["Quvvatning o‘lchov birligi nima?","Vatt","Volt","Amper","Tesla"],
["Yorug‘lik vakuumda taxminan qanday tezlikda tarqaladi?","300 000 km/s","30 000 km/s","3 000 km/s","1 000 000 km/s"],
["Fotosintez jarayonida o‘simliklar qaysi gazni yutadi?","Karbonat angidrid","Kislorod","Azot","Vodorod"],
["Odam qaysi a’zo yordamida nafas oladi?","O‘pka","Jigar","Buyrak","Oshqozon"],
["Qonning qizil rangini nima beradi?","Gemoglobin","Insulin","Kollagen","Keratin"],
["DNK nimani saqlaydi?","Irsiy ma’lumotni","Faqat suvni","Energiya","Kislorodni"],
["Atomning markaziy qismi nima deyiladi?","Yadro","Elektron qobig‘i","Molekula","Ion"],
["Yer atmosferasida eng ko‘p uchraydigan gaz qaysi?","Azot","Kislorod","Karbonat angidrid","Vodorod"],
["Kislota va ishqor reaksiyasida odatda nima hosil bo‘ladi?","Tuz va suv","Faqat gaz","Faqat metall","Faqat kislorod"],
["O‘simliklarda suv asosan qaysi qism orqali so‘riladi?","Ildiz","Barg","Gul","Meva"],
["Inson miyasining asosiy vazifalaridan biri nima?","Organizm faoliyatini boshqarish","Qonni filtrlash","Ovqat hazm qilish","Kislorod ishlab chiqarish"],
["Qaysi modda xona haroratida suyuq metall?","Simob","Temir","Mis","Alyuminiy"],
["Yerning ichki qatlamlaridan eng tashqarisidagi qattiq qatlam nima?","Yer po‘sti","Yadro","Mantiya","Magmatik qatlam"]
],

"Sport": [
["Futbol jamoasida maydonda nechta o‘yinchi bo‘ladi?","11","9","10","12"],
["Basketbolda bir jamoada maydonda nechta o‘yinchi bo‘ladi?","5","6","7","8"],
["Olimpiya ramzida nechta halqa bor?","5","4","6","7"],
["Tennisda 0 ochko qanday ataladi?","Love","Zero","Start","Nil"],
["Futbol bo‘yicha Jahon chempionati odatda necha yilda bir marta o‘tkaziladi?","4","2","3","5"],
["Marafon masofasi taxminan qancha?","42,195 km","21 km","50 km","100 km"],
["Boks ringida nechta burchak mavjud?","4","3","5","6"],
["Voleybol jamoasida maydonda nechta o‘yinchi bo‘ladi?","6","5","7","8"],
["Shaxmat taxtasida nechta katak bor?","64","32","72","81"],
["Shaxmatda eng kuchli dona qaysi?","Farzin","Ot","Fil","Piyoda"],
["Futbolda darvozabon qo‘l bilan asosan qayerda o‘ynashi mumkin?","Jarima maydonida","Butun maydonda","Markaziy doirada","Raqib jarima maydonida"],
["Formula-1 qanday sport turi?","Avtopoyga","Velopoyga","Suzish","Yengil atletika"],
["Dzyudo qaysi davlatda paydo bo‘lgan?","Yaponiya","Xitoy","Koreya","Hindiston"],
["Taekvondo qaysi davlat bilan bog‘liq?","Janubiy Koreya","Yaponiya","Xitoy","Tailand"],
["Futbolda sariq karta nimani bildiradi?","Ogohlantirish","Gol","O‘yindan chetlatish","Tanaffus"],
["Futbolda qizil karta nimani anglatadi?","O‘yindan chetlatish","Gol","Ogohlantirish","Almashtirish"],
["Olimpiya o‘yinlari qaysi davrda boshlangan?","Qadimgi Yunoniston","Qadimgi Rim","Misr","Xitoy"],
["Velosipedda nechta g‘ildirak bo‘ladi?","2","1","3","4"],
["Stol tennisi yana qanday nom bilan ataladi?","Ping-pong","Mini tennis","Speed tennis","Indoor tennis"],
["Suzishda qaysi sport anjomidan foydalaniladi?","Suzish ko‘zoynagi","Futbol to‘pi","Shlem faqat","Raketka"]
],

"San’at va kino": [
["Mona Liza asarining muallifi kim?","Leonardo da Vinchi","Pablo Pikasso","Van Gog","Mikelanjelo"],
["‘Yulduzli tun’ asarini kim yaratgan?","Vincent van Gogh","Leonardo da Vinchi","Pikasso","Rembrandt"],
["Pablo Pikasso qaysi san’at yo‘nalishi bilan mashhur?","Kubizm","Barokko","Rokoko","Realizm"],
["Kino san’atining asosiy vositasi nima?","Harakatlanuvchi tasvir","Faqat musiqa","Faqat haykal","Faqat kitob"],
["Oskar mukofoti qaysi soha bilan bog‘liq?","Kino","Sport","Tibbiyot","Geografiya"],
["Haykaltaroshlikda asosiy shakl nima?","Hajmli tasvir","Faqat tovush","Faqat rang","Faqat yozuv"],
["Teatrda sahnada ijro etuvchi shaxs kim?","Aktyor","Muhandis","Sportchi","Tarjimon"],
["Musiqada temp nimani bildiradi?","Ijro tezligini","Ovoz balandligini","Asbob og‘irligini","Matn uzunligini"],
["Pianinoda odatda nechta oq va qora tugma bo‘ladi?","88","61","76","100"],
["Gitara odatda nechta torli bo‘ladi?","6","4","5","8"],
["Opera qanday san’at turi?","Musiqiy-sahnaviy asar","Faqat rasm","Faqat haykal","Sport turi"],
["Baletda asosiy ifoda vositasi nima?","Raqs","Faqat nutq","Faqat rasm","Faqat yozuv"],
["Rembrandt qaysi davlat san’atkori?","Niderlandiya","Fransiya","Italiya","Ispaniya"],
["‘Qichqiriq’ asarini kim yaratgan?","Edvard Munk","Pikasso","Van Gog","Mone"],
["Animatsiya nima?","Harakat taassurotini beruvchi tasvirlar ketma-ketligi","Faqat jonli ijro","Faqat musiqa","Faqat fotografiya"],
["Kinoda rejissyorning asosiy vazifalaridan biri nima?","Film ijodiy jarayonini boshqarish","Faqat chipta sotish","Kamerani sotish","Tomoshabinlarni sanash"],
["Portret nimani tasvirlaydi?","Inson qiyofasini","Tabiatni","Binoni","Hayvonot bog‘ini"],
["Peyzaj asosan nimani tasvirlaydi?","Tabiat manzarasini","Inson yuzini","Musiqani","Sport musobaqasini"],
["Komediya qanday janr?","Kulgili voqealarga asoslangan","Faqat qo‘rqinchli","Faqat hujjatli","Faqat ilmiy"],
["Tragediya odatda qanday voqealarni tasvirlaydi?","Fojiali voqealarni","Faqat kulgili voqealarni","Sport voqealarini","Sayohatni"]
],

"Hayvonot": [
["Quruqlikdagi eng tez hayvon qaysi?","Gepard","Sher","Ot","Yo‘lbars"],
["Dunyodagi eng katta hayvon qaysi?","Ko‘k kit","Fil","Jirafa","Akula"],
["Qaysi hayvon eng uzun bo‘yli quruqlik hayvonlaridan biri?","Jirafa","Fil","Ot","Yo‘lbars"],
["Pingvinlar asosan qaysi hudud bilan bog‘liq?","Janubiy yarimshar","Shimoliy qutb","Sahroi Kabir","Amazonka"],
["Qaysi hayvon ‘o‘rmon qiroli’ deb ataladi?","Sher","Bo‘ri","Fil","Ayiq"],
["Fillar nima bilan mashhur?","Katta tana va uzun xartumi bilan","Ucha olishi bilan","Suv ostida nafas olishi bilan","Rangini o‘zgartirishi bilan"],
["Delfin qaysi hayvonlar guruhiga kiradi?","Sutemizuvchilar","Baliqlar","Sudralib yuruvchilar","Qushlar"],
["Akula qaysi guruhga kiradi?","Baliqlar","Sutemizuvchilar","Qushlar","Hasharotlar"],
["Qushlarning tanasi nima bilan qoplangan?","Pat","Jun","Tangacha","Qalin teri"],
["Ilonlar qaysi guruhga kiradi?","Sudralib yuruvchilar","Sutemizuvchilar","Qushlar","Baliqlar"],
["Asalarilar qaysi guruhga kiradi?","Hasharotlar","Sutemizuvchilar","Qushlar","Sudralib yuruvchilar"],
["O‘rgimchakning nechta oyog‘i bor?","8","6","10","12"],
["Hasharotlarning odatda nechta oyog‘i bo‘ladi?","6","4","8","10"],
["Kapalakning hayot aylanishida qaysi bosqich mavjud?","G‘umbak","Jo‘ja","Kuchuk","Bola"],
["Tuya cho‘lda yashashga qanday moslashgan?","Suvsiz uzoq yurishga moslashgan","Ucha oladi","Suv ostida yashaydi","Qishda uxlaydi"],
["Qaysi hayvon tuxum qo‘yadi?","Tovuq","Sigir","Ot","Mushuk"],
["Koala qaysi davlat bilan bog‘liq?","Avstraliya","Kanada","Misr","Braziliya"],
["Panda asosan nima bilan oziqlanadi?","Bambuk","Go‘sht","Baliq","Meva faqat"],
["Bo‘ri qaysi hayvonlar guruhiga kiradi?","Sutemizuvchi","Sudralib yuruvchi","Qush","Baliq"],
["Qaysi hayvon rangini o‘zgartira olishi bilan mashhur?","Xameleon","Fil","Ot","Pingvin"]
]

};
